HAI
WAZZUP
I HAS A thing
I HAS A thing2 ITZ "some"
I HAS A thing3 ITZ 3.14
BUHBYE
VISIBLE "HELLO WORLD"
VISIBLE 1.2
VISIBLE 3.14
VISIBLE WIN
VISIBLE FAIL
VISIBLE SUM OF 2 AN 4
VISIBLE DIFF OF 4 AN 3
VISIBLE PRODUKT OF 2 AN 7
VISIBLE QUOSHUNT OF 5 AN 12
VISIBLE MOD OF 3.2 AN 3.14
VISIBLE BIGGR OF 3.2 AN 3.14
VISIBLE SMALLR OF 3.2 AN 3.14
VISIBLE BOTH OF WIN AN FAIL
VISIBLE EITHER OF WIN AN FAIL
VISIBLE WON OF WIN AN FAIL
VISIBLE NOT WIN
KTHXBYE
