HAI
    WAZZUP
    I HAS A temp ITZ SUM OF 2 AN 1
    BUHBYE
    VISIBLE "LOOP: var = " + temp

	IM IN YR desc NERFIN YR temp TIL BOTH SAEM temp AN 0
		VISIBLE "THIS IS STATEMENT 1"
        VISIBLE "THIS IS STATEMENT 2"
	IM OUTTA YR desc

    VISIBLE "OKAYYYYYYYYYYYYYYYYYYYYY"
    
KTHXBYE