1:
	lex GABINETEKG_exer3.l
	cc lex.yy.c -o GABINETEKG_exer3.out -lfl
	./GABINETEKG_exer3.out sampleA.txt

2:
	lex GABINETEKG_exer3.l
	cc lex.yy.c -o GABINETEKG_exer3.out -lfl
	./GABINETEKG_exer3.out sampleB.txt

sample:
	lex GABINETEKG_exer3.l
	cc lex.yy.c -o GABINETEKG_exer3.out -lfl
	./GABINETEKG_exer3.out sample_input.txt

clean:
	rm -f *.out